/**
* @description : Day of week     
* @param {doW}
* @return Input the month day and year and display the respected day of week
*/

dayofWeek = (m, d, y) => {
    try { /* Declaring variables for obtaining the formula */
        let y0 = y - Math.trunc((14 - m) / 12);
        let x = y0 + Math.trunc(y0 / 4) - Math.trunc(y0 / 100) + Math.trunc(y0 / 400);
        let m0 = m + 12 * Math.trunc((14 - m) / 12) - 2;
        d0 = (d + x + Math.trunc(31 * m0 / 12)) % 7;
        /* Switch that will convert the value generated by d0 formula to respected day of week */
        switch (d0) {
            case 0: return "Sunday";
            case 1: return "Monday";
            case 2: return "Tuesday";
            case 3: return "Wednesday";
            case 4: return "Thursday";
            case 5: return "Friday";
            case 6: return "Saturday";
        }

    } catch (error) {
        console.log(error)
    }
}
module.exports = { dayofWeek }
